### ISSUE TITLE
State updates causes cursor to reset its position in input elements

### ISSUE THREAD

**Issue by JoelBesada** [tictail/tide#11]
Whenever you type something in an input that is connected to the state in Tide, it resets the position of the cursor:

![tide-bug](https://cloud.githubusercontent.com/assets/688415/19895108/c57ca892-a04f-11e6-9034-02bd46003cd5.gif)

You can reproduce this issue in the current example app. 

This issue was introduced in `1.0.0-beta` when we changed state updates to be deferred. React requires the value to update on the same call stack as the `onChange` event was triggered, as explained in [this Stack Overflow answer](http://stackoverflow.com/questions/28922275/in-reactjs-why-does-setstate-behave-differently-when-called-synchronously/28922465#28922465).

I'm not sure there's anything we can do to fix this issue while still deferring the update, and if there is the solution is probably not going to be very elegant. Here are some different changes we could make to work around the issue:

* Remove the defer functionality completely
* Instruct developers to manually call `this.tide.emit()` (and maybe add a `this.emit()` shorthand into actions) when updating the state in response to a input change callback.
* Add a flag `mutate(..., {defer: false})`
* Remove the deferring and provide another simple way to batch updates (which is why this was introduced in the first place). Maybe accept an object in mutate: `mutate({'foo.bar': a, 'foo.baz': b})`? 

Ping @eldh

**Comment by eldh** [comment]
- Removing the defer functionality is not an option imo, it's crucial for performance. Only nice way we could do this is that I can see is to rewrite how actions work completely. With the current api (exposing `this.mutate`) batching has to be the default, otherwise making bad perf decisions becomes too easy. 
- In choosing between `this.emit()` and `{defer: false}` I'm leaning a bit towards `{immediate: true}` or something like that :). I would expect any options not passed would default to false, that's why `{defer: false}` feels not so nice.

**Comment by eldh** [comment]
I guess we could also provide a TideInput component that handles it by keeping local state.

**Comment by JoelBesada** [comment]
Okay, I think `{immediate: true}` sounds like the best way forward in that case. TideInput is an interesting solution but not as simple as just having the flag in `mutate`. There might also be other cases where you need to update synchronously that aren't related to an input element.

**Comment by eldh** [comment]
Yeah, sounds good to me 👍
